package com.metarnet.noc.park.webservice.hello;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-06-24T16:47:17.268+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "HelloServiceImplService", 
                  wsdlLocation = "http://192.168.8.33/services/helloService?wsdl",
                  targetNamespace = "http://Hello.webservice.park.noc.metarnet.com/") 
public class HelloServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Hello.webservice.park.noc.metarnet.com/", "HelloServiceImplService");
    public final static QName HelloServiceImplPort = new QName("http://Hello.webservice.park.noc.metarnet.com/", "HelloServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.8.33/services/helloService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.8.33/services/helloService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public IHelloService getHelloServiceImplPort() {
        return super.getPort(HelloServiceImplPort, IHelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "HelloServiceImplPort")
    public IHelloService getHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloServiceImplPort, IHelloService.class, features);
    }

}
